### ISSUE TITLE
Only first occurrence of special char in content type gets escaped

### ISSUE THREAD

**Issue by HannesT117** [contentful-labs/cf-content-types-generator#13]
Hello!

This issue is connected to #11: Since `moduleName` only uses `replace` instead of `replaceAll`, only the first occurrence of a special char in `input` gets replaced. For example:
```
Input: "3-0-Test"
Expected: "Type3__0__Test"
Actual: "Type3__0-Test"
```

**Comment by marcolink** [comment]
@HannesT117 
Thanks for the catch! If you have time i would be very happy to see a PR for that, if not, i can try to squeeze it in asap.

**Comment by HannesT117** [comment]
Done :)

**Comment by marcolink** [comment]
@HannesT117 
would be interested to know if everything works now for you :)

**Comment by HannesT117** [comment]
@marcolink yes, the export seems to be successful now, thanks for asking!
