### ISSUE TITLE
🐛 TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hanna-greaves** [contentful-labs/cf-content-types-generator#18]
Hi there! 

I'm working on a Contentful project at the moment and was looking for a way to generate some simple types :) This project seems super helpful, but I had an issue getting started in that any call would result in 
`TypeError: Cannot read property 'length' of undefined`

The error is coming from unguarded checks on the `length` of the `validations` property in a few places in code. It seems like either a) the contentful specification has been updated since this code was written and `validations` is no longer strictly required, or b) our content model is a bit off :) 

Either way it seems like it would be nice to guard against this check for other users! I have a change ready if you are open to PRs

~Hanna

**Comment by marcolink** [comment]
Hi @hanna-greaves,

thanks for reporting this! 
A PR from your side would be very welcome!

**Comment by hanna-greaves** [comment]
Hey @marcolink, sorry for the delay! I've opened a PR for this now :)
