### ISSUE TITLE
Plans to sync with Gatsby?

### ISSUE THREAD

**Issue by bsgreenb** [contentful-labs/cf-content-types-generator#45]
This looks really cool.  The challenge for gatsby/TS users is that Gatsby's schema isn't aligned.  We have to do overrides like https://gist.github.com/bsgreenb/05202d74c7ef079970b536fad0fc5c88

So don't think this tool would help us?  Any recommendations?

**Comment by marcolink** [comment]
Hi @bsgreenb,

that's an interesting question, I haven't thought about it yet.

How did you generate the types mentioned? '
Also, I wonder what's missing from the types you provided?

best
marco

**Comment by bsgreenb** [comment]
Hey @marcolink 

I use graphql codegen, import the generated types, then modify them.

What's missing is ability to distinguish required fields from not, so I need to manually un-null them.

**Comment by marcolink** [comment]
@bsgreenb 

unfortunately, I don't see how this could play together. If I understand it right, the types you generate are in the context of GraphQL, with all GraphQL specific fields and so on. Currently, this library only creates plain types for your content models, without any additional information.
